export const BUS_LINES = [
  { id: "01", gid: "1451641928", go: "NOVO HORIZONTE"          , to: "CIDADE NOVA"   , note:"VIA SÃO GERALDO" },
  { id: "02", gid: "1716538182", go: "ROMEU DUARTE"            , to: "GAMAS"         , note:"VIA CAPÃO" },
  { id: "03", gid: "923141346" , go: "ROMEU DUARTE"            , to: "CONCESSO ELIAS", note:"VIA UPA24H" },
  { id: "04", gid: "730538672" , go: "SUNSET (SENAI)"          , to: "MARIA RITA"    , note:"VIA ITAPUÃ" },
  { id: "05", gid: "696430486" , go: "VEREDAS"                 , to: "BOA VISTA"     , note:"VIA ANTÔNIO VENÂNCIO" },
  { id: "06", gid: "283748373" , go: "CENTRO"                  , to: "CAPÃO"         , note:"" },
  { id: "07", gid: "794025811" , go: "CONCESSO ELIAS"          , to: "SÃO JOSÉ"      , note:"VIA SÃO GERALDO" },
  { id: "08", gid: "880379305" , go: "RODOVIÁRIA"              , to: "AREIAS"        , note:"VIA JARDIM DO LAGO" },
  { id: "09", gid: "1247839437", go: "DONA ZELI"               , to: "BARRETOS"      , note:"VIA POUSO ALEGRE E CENTRO" },
  { id: "10", gid: "1967161081", go: "DONA ZELI"               , to: "SÃO JOSÉ"      , note:"VIA SANTANA" },
  // { id: "11", gid: "1744983634", go: "E. FREI ANSELMO"         , to: "E. MARIA ZELI - SÃO GERALDO - CIDADE NOVA"  , note:"" },
  // { id: "12", gid: "930151049" , go: "E. MARIA ZELI"           , to: "GAMAS - RIPAS - FAZENDA PARANÁ"             , note:"" },
  // { id: "13", gid: "1361448193", go: "E. ANTÔNIO MARTINS"      , to: "CONCESSO ELIAS"                             , note:"VIA E. MARIA ZELI" },
  // { id: "14", gid: "138008490" , go: "E. MARIA ZELI"           , to: "E. PADRE LAURO - REGINA AMARAL - MARIA RITA", note:"" },
  // { id: "15", gid: "143766065" , go: "E. MARIA ZELI"           , to: "BOA VISTA"                                  , note:"VIA E. ANTÔNIO MARTINS " },
  // { id: "16", gid: "1071806207", go: "E. MARIA ZELI"           , to: "CAPÃO"                                      , note:"VIA E. ANTÔNIO MARTINS" },
  // { id: "17", gid: "1442834386", go: "VEREDAS"                 , to: "E. PADRE LAURO"                             , note:"VIA CONCESSO ELIAS" },
  // { id: "18", gid: "1442255353", go: "MARIA RITA - SANTA SARA" , to: "E. PADRE LAURO"                             , note:"" },
  // { id: "19", gid: "803392761" , go: "E. FREI ANSELMO"         , to: "E. MARIA DO CARMO"                          , note:"VIA SÃO SEBASTIÃO" },
];